import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MSWProvider } from '@/app/_component/MSWComponent';
import AuthSession from '@/app/_component/AuthSession';

if (process.env.NEXT_RUNTIME === 'nodejs' && process.env.NODE_ENV !== 'production' && process.env.MSW_ENABLED !== 'false') {
    const { server } = require('@/mocks/http')
    server.listen()
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'ZCom',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode,
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <MSWProvider>
                    <AuthSession>
                        {children}
                    </AuthSession>
                </MSWProvider>
            </body>
        </html>
    );
}
